name: Pull Request Check
on:
  pull_request:
    branches:
      - main

jobs:
  yaml-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Run YAML linter
        run: yamllint .

      - name: Success
        run: echo "Success"