---
name: Crime Data CICD
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Testing:
    uses: ./.github/workflows/test.yml
    with:
      environ: Dev
    secrets:
      raw_data_path: ${{ secrets.raw_data_path }}
      target_path: ${{ secrets.target_path }}

  Dev:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
      - name: Dev
        run: echo "hi"
