name: Crime Data CICD
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  Testing:
    environment: Test
    uses: ./.github/workflows/test.yml
    with:
      raw_data_path: ${{ secrets.raw_data_path }}


  Dev:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
      - name: Dev
        run: echo "hi"