name: Crime Data CICD
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  Testing:
    environment: Dev
    env:
      RAW_DATA_PATH: ${{ secrets.Raw_Data_Path }}
    uses: ./.github/workflows/test.yml

  Dev:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
      - name: Dev
        run: echo "hi"