---
name: Crime Data CICD
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Testing:
    uses: ./.github/workflows/test.yml
    with:
      environ: Dev
      raw_data_path: ${{ secrets.raw_data_path }}

  Dev:
    runs-on: ubuntu-latest
    needs: Testing
    environment: Dev
    env:
      raw_data_path: ${{ secrets.raw_data_path }}
      target_path: ${{ secrets.target_path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Transform and write data
        run: python notebooks/pipeline.py
