name: Crime Data CICD
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  Testing:
    environment: Dev
    uses: ./.github/workflows/test.yml
    with:
      RAW_DATA_PATH: ${{ secrets.Raw_Data_Path }}


  Dev:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
      - name: Dev
        run: echo "hi"