---
name: Crime Data CICD
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Testing:
    uses: ./.github/workflows/test.yml
    with:
      environ: Dev
    secrets: inherit

  Dev:
    runs-on: ubuntu-latest
    needs: Testing
    environment: Dev
    env:
      raw_data_path: ${{ secrets.raw_data_path }}
      target_path: ${{ secrets.target_path }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Transform and write data
        run: python notebooks/pipeline.py

  Report on Teams:
    needs: [Testing, Dev]
    if: failure()
    uses: ./.github/workflows/send-teams-message.yml
    with:
      job_name: Test Job
      status: Success
      failure_reason: No reason
    secrets: inherit