name: Crime Data CICD
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  Testing:
    uses: ./.github/workflows/test.yml

  Dev:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
      - name: Dev
        run: echo "hi"