name: Matrix Workflow
on:
  push:
    branch:
      - main
      - 'dev*'

jobs:
  build:
    strategy:
      matrix:
        Workspace: [Dev, UAT, Prod]
        Designation: [IT, Tax]
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Environment
        run: echo "${{ matrix.Designation }}"
      - name: Branch
        run: echo "${{ matrix.Workspace }}"
