name: Reusable Workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of test file generated
        required: false
        default: test
        type: string
#    secrets:
#      some-secret:
#        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List Files
        run: ls
      - name: Deploy code
        run: echo "Uploading and Deploying"