name: Testing

on:
  workflow_call:
    inputs:
      environ:
        required: true
        type: string
    secrets:
      raw_data_path:
        required: true


jobs:
  Install_Dependencies:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environ }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test Data
        env:
          raw_data_path: ${{ inputs.raw_data_path }}
        run: pytest tests
          
