---
name: Testing

on:
  workflow_call:
    inputs:
      environ:
        required: true
        type: string

jobs:
  Install_Dependencies:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environ }}
    env:
      raw_data_path: ${{ secrets.raw_data_path }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout code and install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Test Data
        run: pytest tests
