name: Test Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
#      - name: Install Spark
#        uses: vemonet/setup-spark@v1
#        with:
#          spark-version: '3.5.3'
#          hadoop-version: '3'
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Testing the data
        run: pytest tests/test_pipeline.py

  Dev:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: print hi
        run: echo "print hi"
