name: Test Workflow
on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - 'dev-*'
      - 'dev/**'
  workflow_dispatch: # Even we are not using any option here but still we have to use colon for every trigger
  push:
    branches:
      - main
      - 'dev-*' # dev-new dev-this-is-new
      - 'dev/**' # dev/new_feat/new_change
#    paths-ignore:
#      - '.github/workflows/*' # If i push the change in workflow folder, the GitHub workflow won't start.
#    paths:
#      - 'notebooks/**' # Workflow will start only, if we do changes in these paths


jobs:
  TEST:
    environment: Testing
    env:
      DATA_FILE_PATH: ${{ vars.DATA_FILE_PATH }}
      DATA_FILE_NAME: ${{ secrets.DATA_FILE_NAME }}

    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
#      - name: Install Spark
#        uses: vemonet/setup-spark@v1
#        with:
#          spark-version: '3.5.3'
#          hadoop-version: '3'
      - name: Cache Dependencies
        id: cache_check
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Install Dependencies
        if: steps.cache_check.outputs.cache-hit != 'true'
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest and generate xml report
        continue-on-error: true
        id: testing_data
        run: pytest tests/test_pipeline.py --junitxml=test_results.xml

      - name: Upload test results
#        if: failure() && steps.testing_data.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: test_results.xml

      - name: Publish test results in GitHub UI
#        if: failure() && steps.testing_data.outcome == 'failure'
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: 'test_results.xml'
          check_name: 'Pytest Results'

      - name: Testing Data File Path and Name
        run: |
          echo "Data File Path: $DATA_FILE_PATH"
          echo "Data File Name: $DATA_FILE_NAME"

  Testing:
    needs: TEST
    uses: ./.github/workflows/reusable.yml
    with:
      artifact-name: pytest-results

  Dev:
    needs: TEST
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache Dependencies
        id: cache_check
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Install Dependencies
        if: steps.cache_check.outputs.cache-hit != 'true'
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: print Test File Name
        run: echo "print $DATA_FILE_NAME"

  Report:
    needs: [TEST, Dev]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output Information
        run: |
          echo "Something went wrong"
          echo "${{ toJSON(github) }}"

